import type { StockItem, Supplier, Project, BOQItem, RFQ, StockMovement } from "./types"

export const mockStockItems: StockItem[] = [
  {
    id: "1",
    name: "Single Mode Fiber Cable",
    category: "Fibre",
    unitOfMeasure: "meters",
    quantityInStock: 5000,
    minimumStock: 1000,
    supplierId: "1",
    lastPurchasePrice: 2.5,
    warehouseLocation: "A-01",
    status: "In Stock",
    itemCode: "SMF-001",
    description: "Single mode fiber optic cable for long distance transmission",
  },
  {
    id: "2",
    name: "Concrete Pole 9m",
    category: "Poles",
    unitOfMeasure: "pieces",
    quantityInStock: 50,
    minimumStock: 20,
    supplierId: "2",
    lastPurchasePrice: 150.0,
    warehouseLocation: "B-01",
    status: "In Stock",
    itemCode: "CP-9M",
    description: "9 meter concrete utility pole",
  },
  {
    id: "3",
    name: "Fiber Splice Closure",
    category: "Equipment",
    unitOfMeasure: "pieces",
    quantityInStock: 15,
    minimumStock: 25,
    supplierId: "1",
    lastPurchasePrice: 85.0,
    warehouseLocation: "C-01",
    status: "Low Stock",
    itemCode: "FSC-001",
    description: "Weatherproof fiber splice closure",
  },
  {
    id: "4",
    name: "Fusion Splicer",
    category: "Tools",
    unitOfMeasure: "pieces",
    quantityInStock: 3,
    minimumStock: 2,
    supplierId: "3",
    lastPurchasePrice: 2500.0,
    warehouseLocation: "D-01",
    status: "In Stock",
    itemCode: "FS-001",
    description: "Professional fiber fusion splicer",
  },
  {
    id: "5",
    name: "Cable Ties",
    category: "Consumables",
    unitOfMeasure: "pieces",
    quantityInStock: 0,
    minimumStock: 500,
    supplierId: "2",
    lastPurchasePrice: 0.15,
    warehouseLocation: "E-01",
    status: "Out of Stock",
    itemCode: "CT-001",
    description: "UV resistant cable ties",
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "FiberTech Solutions",
    contactPerson: "John Smith",
    email: "john@fibertech.com",
    phone: "+1-555-0101",
    address: "123 Tech Street, Silicon Valley, CA",
    paymentTerms: "Net 30",
    rating: 4.5,
  },
  {
    id: "2",
    name: "Infrastructure Supply Co.",
    contactPerson: "Sarah Johnson",
    email: "sarah@infrasupply.com",
    phone: "+1-555-0102",
    address: "456 Industrial Ave, Houston, TX",
    paymentTerms: "Net 45",
    rating: 4.2,
  },
  {
    id: "3",
    name: "Precision Tools Ltd.",
    contactPerson: "Mike Chen",
    email: "mike@precisiontools.com",
    phone: "+1-555-0103",
    address: "789 Equipment Blvd, Denver, CO",
    paymentTerms: "Net 15",
    rating: 4.8,
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Downtown Fiber Network",
    projectManager: "Alice Cooper",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    status: "Active",
    location: "Downtown District",
    budget: 250000,
  },
  {
    id: "2",
    name: "Suburban Expansion Phase 1",
    projectManager: "Bob Wilson",
    startDate: "2024-03-01",
    endDate: "2024-09-15",
    status: "Active",
    location: "Suburban Area North",
    budget: 180000,
  },
  {
    id: "3",
    name: "Industrial Park Connection",
    projectManager: "Carol Davis",
    startDate: "2024-05-01",
    endDate: "2024-08-31",
    status: "Planned",
    location: "Industrial Park West",
    budget: 120000,
  },
]

export const mockBOQItems: BOQItem[] = [
  {
    id: "1",
    projectId: "1",
    stockItemId: "1",
    requiredQuantity: 2000,
    allocatedQuantity: 1500,
    remainingQuantity: 500,
    unitPrice: 2.5,
    totalPrice: 5000,
    status: "Partially Allocated",
  },
  {
    id: "2",
    projectId: "1",
    stockItemId: "2",
    requiredQuantity: 25,
    allocatedQuantity: 25,
    remainingQuantity: 0,
    unitPrice: 150.0,
    totalPrice: 3750,
    status: "Fully Allocated",
  },
  {
    id: "3",
    projectId: "2",
    stockItemId: "1",
    requiredQuantity: 1500,
    allocatedQuantity: 0,
    remainingQuantity: 1500,
    unitPrice: 2.5,
    totalPrice: 3750,
    status: "Planned",
  },
]

export const mockRFQs: RFQ[] = [
  {
    id: "1",
    supplierId: "1",
    projectId: "1",
    rfqDate: "2024-01-20",
    dueDate: "2024-02-05",
    status: "Open",
    totalEstimatedAmount: 15000,
    items: [
      {
        id: "1",
        stockItemId: "1",
        quantity: 3000,
        estimatedPrice: 2.5,
      },
      {
        id: "2",
        stockItemId: "3",
        quantity: 50,
        estimatedPrice: 85.0,
      },
    ],
  },
]

export const mockStockMovements: StockMovement[] = [
  {
    id: "1",
    stockItemId: "1",
    type: "Addition",
    quantity: 1000,
    date: "2024-01-15",
    performedBy: "John Doe",
    notes: "New stock delivery from FiberTech Solutions",
  },
  {
    id: "2",
    stockItemId: "1",
    type: "Site Allocation",
    quantity: -500,
    date: "2024-01-20",
    performedBy: "Alice Cooper",
    notes: "Allocated to Downtown Fiber Network project",
    projectId: "1",
  },
  {
    id: "3",
    stockItemId: "2",
    type: "Consumption",
    quantity: -5,
    date: "2024-01-22",
    performedBy: "Bob Wilson",
    notes: "Used for suburban expansion installation",
  },
]
